# Generated by Django 5.0.6 on 2024-06-06 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('can_view_mailings', 'Can view mailings'), ('can_disable_mailings', 'Can disable mailings')]},
        ),
    ]
